---
kind: Template
apiVersion: v1
metadata:
  name: dokuwiki-standalone
  annotations:
    openshift.io/display-name: DokuWiki
    description: Creates a DokuWiki installation. Requires one persistent volume be available. 
    tags: php,dokuwiki
    iconClass: icon-php
parameters:
- name: APPLICATION_NAME
  description: The name of the DokuWiki instance.
  value: tirant 
  from: "[a-zA-Z0-9]"
  required: true
- name: DOKUWIKI_USERNAME
  description: The superuser name of the DokuWiki instance.
  value: superuser
  from: "[a-zA-Z0-9]"
  required: true 
- name: DOKUWIKI_PASSWORD 
  description: The superuser password of the DokuWiki instance.
  value: bitnami1 
  from: "[a-zA-Z0-9]"
  required: true 
- name: DOKUWIKI_EMAIL 
  description: The superuser email of the DokuWiki instance.
  value: test@gmail.com 
  from: "[a-zA-Z0-9]"
  required: true 
- name: DOKUWIKI_WIKI_NAME 
  description: The title of the DokuWiki instance.
  value: "Bitnami DokuWiki" 
  from: "[a-zA-Z0-9]"
  required: true 
- name: DOKUWIKI_VOLUME_SIZE
  description: Size of the persistent volume for Wordpress.
  value: 1Gi
  required: true
- name: DOKUWIKI_VOLUME_TYPE
  description: Type of the persistent volume for Wordpress.
  value: ReadWriteOnce
  required: true
- name: DOKUWIKI_DEPLOYMENT_STRATEGY
  description: Type of the deployment strategy for Wordpress.
  value: Recreate
  required: true
- name: DOKUWIKI_MEMORY_LIMIT
  description: Amount of memory available to WordPress.
  value: 512Mi
  required: true
objects:
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-img"
    labels:
      app: "${APPLICATION_NAME}"
- kind: BuildConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    triggers:
    - type: ConfigChange
    - type: ImageChange
    source:
      type: Dockerfile
      dockerfile: |-
        FROM bitnami/dokuwiki 
        EXPOSE 8080
    strategy:
      dockerStrategy:
        forcePull: true
        from:
          kind: DockerImage 
          name: bitnami/dokuwiki:latest
      type: Docker
    triggers:
    - type: ConfigChange
    output:
      to:
        kind: ImageStreamTag
        name: "${APPLICATION_NAME}-img:latest"
      imageLabels:
      - name: io.k8s.display-name
        value: DokuWiki 
      - name: io.k8s.description
        value: DokuWiki application and S2I builder.
      - name: io.openshift.s2i.scripts-url
        value: image:///opt/app-root/s2i
      - name: io.s2i.scripts-url
        value: image:///opt/app-root/s2i
      - name: io.openshift.tags
        value: builder,php,dokuwiki
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    strategy:
      type: "${DOKUWIKI_DEPLOYMENT_STRATEGY}"
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - dokuwiki 
        from:
          kind: ImageStreamTag
          name: "${APPLICATION_NAME}-img:latest"
    replicas: 1
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
    template:
      metadata:
        labels:
          app: "${APPLICATION_NAME}"
          deploymentconfig: "${APPLICATION_NAME}"
      spec:
        volumes:
        - name: data
          persistentVolumeClaim:
            claimName: "${APPLICATION_NAME}-dokuwiki-data"
        containers:
        - name: dokuwiki 
          image: "${APPLICATION_NAME}-img"
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              memory: "${DOKUWIKI_MEMORY_LIMIT}"
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: "/doku.php"
              port: 80
              scheme: HTTP
              httpHeaders:
              - name: X-Forwarded-Proto
                value: https
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: "/doku.php"
              port: 80
              scheme: HTTP
              httpHeaders:
              - name: X-Forwarded-Proto
                value: https
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
          - name: APACHE_HTTP_PORT_NUMBER
            value: "8080"
          - name: APACHE_SET_HTTPS_PORT 
            value: "no"
          - name: DOKUWIKI_USERNAME
            value: "${DOKUWIKI_USERNAME}"
          - name: DOKUWIKI_PASSWORD
            value: "${DOKUWIKI_PASSWORD}"
          - name: DOKUWIKI_EMAIL
            value: "${DOKUWIKI_EMAIL}"
          - name: DOKUWIKI_WIKI_NAME
            value: "${DOKUWIKI_WIKI_NAME}"
          volumeMounts:
          - name: data
            mountPath: "/bitnami"
- kind: Service
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    ports:
    - name: 80-tcp
      protocol: TCP
      port: 80
      targetPort: 80
    selector:
      app: "${APPLICATION_NAME}"
      deploymentconfig: "${APPLICATION_NAME}"
- kind: Route
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    host: ''
    to:
      kind: Service
      name: "${APPLICATION_NAME}"
      weight: 100
    port:
      targetPort: 80
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Allow
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: "${APPLICATION_NAME}-dokuwiki-data"
    labels:
      app: "${APPLICATION_NAME}"
  spec:
    accessModes:
    - "${DOKUWIKI_VOLUME_TYPE}"
    resources:
      requests:
        storage: "${DOKUWIKI_VOLUME_SIZE}"
